### ISSUE TITLE
HIVE appender ?

### ISSUE THREAD

**Issue by winwisely99** [Ephenodrom/Dart-Log-4-Dart-2#1]
Hive is a simple KV store that works in Web, Desktop and Mobile.
It also has AES encryption.

Can you consider supporting HIVE ?

Here is an example: https://github.com/mdrideout/flutter_hive_provider_example

**Comment by Ephenodrom** [comment]
Sounds like a good idea, will take a look into HIVE. It will take a few days.

**Comment by winwisely99** [comment]
thank you !!

will look into code to sync it back to the Server once done


Telegram ( as gedw99 )
http://t.me/gedw99

**Comment by Ephenodrom** [comment]
@winwisely99 
I was just checking the documentation yesterday and I need some more information :

Where would you use this package ? ( Flutter Native App, Flutter Web App, Dart Native, Dart Web )

Should all logs be stored in a seperate box ?

Should all logs be stored in the same key ?

What i thought about :
```dart
var box = await Hive.openBox('log4dart');
var record = LogRecord();
// ... some code
box.add(record);
```

**Comment by Ephenodrom** [comment]
No feedback so far. Will close the issue.

**Comment by winwisely99** [comment]
Hey @Ephenodrom 

Sorry about missing in action.

We use it in all flutter targets ( web desktop mobile and raspberry pi ).

Hive works fine in all.

Separation of boxes.. yes and no 

1. Framework level logs go to that log file / hive.

2. User level logs ( the actual app later using the packages go to user level.

We do this for security reasons in that user and system data should not cross leak as they have different encryption keys and requirements 

I have been sick and doing admin but now am around and working

**Comment by Ephenodrom** [comment]
@winwisely99 
Another thing to consider, this package will not run on flutter web. Due to the use of dart:io it will only run as a native application, if you still want to use the package.

Just give me some feedback if this package still meets your requirements. Then I will try to implement the HiveAppender.

**Comment by winwisely99** [comment]
Ah lack of flutter web is a breaker for us.

We use normal hive with encryption on flutter web btw and it works great

So sounds like the need for file appending in you package conflicts with
just hive.

If you split it out into two packages. One that does IK and one that does
IK to dart it should then work ?
But this might not be what meets your goals ?
