### ISSUE TITLE
Wrong dependency name in readme.md

### ISSUE THREAD

**Issue by gui-andrades** [Ephenodrom/Dart-Log-4-Dart-2#6]
I tried to install the package dependency as listed in the Install/pubspec.yaml part of the Readme file, but it resulted in an error saying the package didn't exist. It seems like the correct dependency name is "log_4_dart_2", instead of "log_for_dart_2", since I put that one in my dependencies and it worked.

**Comment by Ephenodrom** [comment]
Fixed with 1.0.0-rc.1
