### ISSUE TITLE
Works well with flutter web? I got an error for fileappender path.

### ISSUE THREAD

**Issue by BehlulKeremSisman** [Ephenodrom/Dart-Log-4-Dart-2#7]

**Comment by Ephenodrom** [comment]
@BehlulKeremSisman 
I havent tried it with Flutter Web and it was not intended to be used with Flutter from the beginning. It should work with Flutter on Mobile and Desktop fine. 

The main goal was to have a file logging that can be used within command line tools and rest server written in Dart.
